openapi: 3.0.1
info:
  title: DemoApi-1
  description: ''
  version: '1.0'
servers:
  - url: https://dev-apim-eus-1.azure-api.net/demoapi1
paths:
  /getdemo:
    get:
      summary: get demo
      operationId: get-demo
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]