openapi: 3.0.1
info:
  title: Process Test Request
  description: ''
  version: v1
servers:
  - url: https://dev-apim-eus-1.azure-api.net/api/v1
paths:
  /getdetails:
    get:
      summary: Get Details
      operationId: get-details
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]