name: Deploy Azure APIM with Bicep

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true

    - name: Install Bicep CLI
      run: |
        az bicep install

    - name: Deploy APIM using Bicep
      run: |
        az deployment group create \
          --resource-group komatsu-poc \
          --template-file ./bicep/modules/APIMinfra.bicep \
          --parameters apiManagementName=t-apim-kx \
                       publisherEmail="souvikg90@gmail.com" \
                       publisherName="Souvik"

    - name: Logout from Azure
      run: az logout
